# services:
#   app:
#     build:
#       context: .
#       dockerfile: docker/php/Dockerfile
#     container_name: laravel_app
#     working_dir: /var/www/html/Todo
#     volumes:
#       - .:/var/www/html/Todo
#     environment:
#       - APP_ENV=local
#     networks:
#       - bridge

#   webserver:
#     build:
#       context: .
#       dockerfile: docker/nginx/Dockerfile
#     container_name: nginx
#     ports:
#       - "8082:80"
#     volumes:
#       - .:/var/www/html/Todo
#       - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf  # Mount Nginx config
#     depends_on:
#       - app
#     networks:
#       - bridge

# networks:
#   bridge:
#     driver: bridge

# volumes:
#   app_socket:  # Define shared volume for the socket



services:
  app:
    image: your-dockerhub/laravel_app:latest
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - /var/www/html/sample-todo/.env:/var/www/html/sample-todo/.env
    networks:
      - bridge

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/www:/var/www
      - /var/www/sample-todo/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - bridge

networks:
  bridge:
    driver: bridge


