- name: To deploy the laravel app
  hosts: 172.16.20.220
  tasks:
  - name: to stop existing image
    command: docker stop laravel_app
    ignore_errors: true

  - name: to delete php container
    command: docker rm php_app
    ignore_errors: true

  - name: to delete php image
    command: docker rmi php_app
    ignore_errors: true

  - name: to build image of php
    command: docker-compose up --build -d

  - name: to build image of php
    shell: docker-compose logs || true


