- name: To deploy the laravel app
  hosts: 127.0.0.1
  tasks:
  - name: to stop existing image
    command: docker stop laravel_app
    ignore_errors: true

  - name: to delete php container
    command: docker rm laravel_app
    ignore_errors: true

  - name: to delete php image
    command: docker rmi laravel_app
    ignore_errors: true

  - name: to stop existing image
    command: docker stop nginx
    ignore_errors: true

  - name: to delete php container
    command: docker rm nginx
    ignore_errors: true

  - name: to delete php image
    command: docker rmi nginx
    ignore_errors: true


  - name: to build image of php
    command: docker-compose up --build -d

  - name: to build image of php
    shell: docker-compose logs || true


