- name: To deploy the laravel app
  hosts: 127.0.0.1
  tasks:
  - name: to stop existing image
    command: docker stop php_app
    ignore_errors: true

  - name: to delete php container
    command: docker rm php_app
    ignore_errors: true

  - name: to delete php image
    command: docker rmi php_app
    ignore_errors: true

  - name: to build image of php
    command: docker-compose up --build -d

  - name: to build image of php
    shell: docker-compose logs || true


