- name: To deploy the laravel app
  hosts: localhosts
  connection: local
  tasks:
  - name: to stop existing image
    command: docker stop php_app
    ignore_errors: yes

  - name: to delete php container
    command: docker rm php_app
    ignore_errors: yes

  - name: to delete php image
    command: docker rmi php_app
    ignore_errors: yes

  - name: to download nginx image
    command: docker pull nginx
    ignore_errors: yes

  - name: to build image of php
    command: docker build -t php_app
    ignore_errors: yes
    args:
      chdir: ./

  - name: to build a container
    command: docker run -d --name php_app -p 8000:80 php_app 
